CRUD_D1/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace CRUD_D1.Models
{
    public class Category
    {
        [Key]
        public int Category_Id { get; set; }
        public string? Category_Name { get; set; }
    }
}

CRUD_D1/Models/ErrorViewModel.cs
namespace CRUD_D1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD_D1/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace CRUD_D1.Models
{
    public class Product
    {
        [Key]
        public int Product_Id { get; set; }
        public string? Product_Name { get; set; }
        public string Product_Img { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int? Category_Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }

    }
}

CRUD_D1/Controllers/CategoryController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_D1.Data;
using CRUD_D1.Models;
using CRUD_D1.Service;

namespace CRUD_D1.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Category
        public IActionResult Index()
        {
            return View(_categoryService.GetCategories());
        }

        // GET: Category/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _categoryService.GetCategory(id);
            if (rs == null)
            {
                return NotFound();
            }

            return View(rs);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Category_Id,Category_Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.AddCategory(category);
                TempData["success"] = "Category added successfully!";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _categoryService.GetCategory(id);
            if (rs == null)
            {
                return NotFound();
            }
            return View(rs);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Category_Id,Category_Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(category);
                TempData["success"] = "Product updated successfully!";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _categoryService.GetCategory(id);
            if (rs == null)
            {
                return NotFound();
            }
            _categoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }

        
    }
}

CRUD_D1/Controllers/HomeController.cs
using CRUD_D1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD_D1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD_D1/Controllers/ProductController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_D1.Data;
using CRUD_D1.Models;
using CRUD_D1.Service;

namespace CRUD_D1.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        // GET: Product
        public IActionResult Index()
        {
            return View( _productService.GetProducts());
        }

        // GET: Product/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _productService.GetProduct(id);
            if (rs == null)
            {
                return NotFound();
            }

            return View(rs);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Product_Id,Product_Name,Product_Img,Description,Price,Category_Id,CreatedDate,UpdatedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                _productService.AddProduct(product);
                TempData["success"] = "Product added successfully!";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _productService.GetProduct(id);
            if (rs == null)
            {
                return NotFound();
            }
            return View(rs);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Product_Id,Product_Name,Product_Img,Description,Price,Category_Id,CreatedDate,UpdatedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                _productService.UpdateProduct(product);
                TempData["success"] = "Product updated successfully!";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rs = _productService.GetProduct(id);
            if (rs == null)
            {
                return NotFound();
            }
            _productService.DeleteProduct(id);
            return RedirectToAction("Index");
        }

        
    }
}

CRUD_D1/Views/Category/Create.cshtml
@model CRUD_D1.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center fw-bold bg-light">Create Category</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category_Name" class="col-sm-2 col-form-label">Category Name</label>
                
                <input asp-for="Category_Name" class="form-control" />
                
                <span asp-validation-for="Category_Name" class="text-danger"></span>
            </div>
            <hr/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD_D1/Views/Category/Details.cshtml
@model CRUD_D1.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category_Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Category_Id" class="btn btnbtn-outline-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
</div>

CRUD_D1/Views/Category/Edit.cshtml
@model CRUD_D1.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center fw-bolder bg-light">Edit Category</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Category_Id" />
            <div class="form-group row">
                <label asp-for="Category_Name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input asp-for="Category_Name" class="form-control" />
                </div>
                <span asp-validation-for="Category_Name" class="text-danger"></span>
            </div>
            <hr/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD_D1/Views/Category/Index.cshtml
@model IEnumerable<CRUD_D1.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center fw-bolder bg-light">Category Admintrasor</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Category_Id)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Category_Name)
            </th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Category_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Category_Id" class="btn btn-warning"><i class="fas fa-edit me-2"></i>Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Category_Id" class="btn btn-info"><i class="fa fa-eye me-2"></i>Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Category_Id" class="btn btn-danger" onclick="return confirm('Are you sure to delete this record?')"><i class="fas fa-trash me-2"></i>Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CRUD_D1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD_D1/Views/Product/Create.cshtml
@model CRUD_D1.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center fw-bolder bg-light">Create Product</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Img" class="control-label"></label>
                <input asp-for="Product_Img" class="form-control" />
                <span asp-validation-for="Product_Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"></input>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category_Id" class="control-label">Category</label>
                <select asp-for="Category_Id" class ="form-select" asp-items="ViewBag.Category_Id">
                    <option value="null">Type</option>
                    <option value="2">Laptop</option>
                    <option value="3">Phone</option>
                </select>
            </div>
            <hr/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD_D1/Views/Product/Details.cshtml
@model CRUD_D1.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_Img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Product_Id" class="btn btn-outline-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
</div>

CRUD_D1/Views/Product/Edit.cshtml
@model CRUD_D1.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center fw-bold bg-light">Edit Product</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Product_Id" />
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Img" class="control-label"></label>
                <input asp-for="Product_Img" class="form-control" />
                <span asp-validation-for="Product_Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category_Id" class="control-label"></label>
                <select asp-for="Category_Id" class ="form-select" asp-items="ViewBag.Category_Id">
                    <option value="null">Type</option>
                    <option value="2">Laptop</option>
                    <option value="3">Phone</option>
                </select>
                <span asp-validation-for="Category_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <hr/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-light">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD_D1/Views/Product/Index.cshtml
@model IEnumerable<CRUD_D1.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center fw-bolder bg-light">Product Admintrasor</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Product_Name)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Product_Img)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th colspan="3"></th>            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Product_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_Img)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Product_Id" class="btn btn-warning"><i class="fas fa-edit me-2"></i>Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Product_Id"  class="btn btn-info"><i class="fa fa-eye me-2"></i>Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Product_Id" onclick="return confirm('Are you sure to delete this record?')" class="btn btn-danger"><i class="fas fa-trash me-2"></i>Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CRUD_D1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_D1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_D1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_D1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Manage Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Manage Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CRUD_D1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>